#include <iostream>

using namespace std;

int main()
{

cout << "=====================================" << endl;
cout << "|  PROSEDUR  UNTUK MENJADI SARJANA |" << endl;
cout << "=====================================" << endl;

	cout << "PROSEDUR SD" << endl;
	cout << "1. Masuk Kelas 1 SD" << endl;
	cout << "2. naik Kelas 2 SD" << endl;
	cout << "3. naik Kelas 3 SD" << endl;
	cout << "4. naik Kelas 4 SD" << endl;
	cout << "5. naik Kelas 5 SD" << endl;
	cout << "6. naik Kelas 6 SD" << endl;
	cout << "7.lulus SD"<< endl;
	cout << "PROSEDUR SMP" << endl;
	cout << "8. Masuk Kelas 7 SMP" << endl;
	cout << "9. naik Kelas 8 SMP" << endl;
	cout << "10. naik Kelas 9 SMP" << endl;
	cout << "11. lulus SMP"<< endl;
	cout << "PROSEDUR SMA" << endl;
	cout << "12. Masuk Kelas 10 SMA" << endl;
	cout << "13. naik Kelas 11 SMA" << endl;
	cout << "14. naik Kelas 12 SMA" << endl;
	cout << "15. lulus SMA"<< endl;
	cout << "PROSEDUR KULIAH" << endl;
	cout << "16. Masuk Kuliah Semester 1" << endl;
	cout << "17. naik Kuliah Semester 2" << endl;
	cout << "18. naik Kuliah Semester 3" << endl;
	cout << "19. naik Kuliah Semester 4" << endl;
	cout << "20. naik Kuliah Semester 5" << endl;
	cout << "21. naik Kuliah Semester 6" << endl;
	cout << "22. naik Kuliah Semester 7" << endl;
	cout << "23. naik Kuliah Semester 8" << endl;
	cout << "24. Wisuda dan Menjadi Sarjana dengan IPK memuaskan" << endl;

return 0;
}